In [1]:
print("Hello world")

Hello world


## We are Learning Numpy

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,2,5]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

2

In [5]:
arr.shape #no of rows and columns

(2, 3)

In [6]:
arr.size # total no of elements

6

In [7]:
arr.dtype

dtype('int32')

In [9]:
arr = np.array([[1,2,3],[4,2,5]], dtype = 'float')
arr

array([[1., 2., 3.],
       [4., 2., 5.]])

In [11]:
e = np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(3) #identity matrix of 3 x 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
f = np.arange(0,30,5)
f # sequential array with step 5 having values between 0-30

array([ 0,  5, 10, 15, 20, 25])

In [19]:
g = np.linspace(0,5,10) # this is used to get the exactly 10 
#values between 0 and 5
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
a = np.random.random((2,2))
a

array([[0.4482865 , 0.56674855],
       [0.06915968, 0.81482299]])

In [27]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr = arr.reshape((4,3))
newarr

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

In [29]:
flat = arr.flatten()
flat

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1])

## Array Indexing

In [34]:
arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,1]])
print(arr[1:,:3:2])

[[5 4]
 [1 0]]


In [35]:
## arr[start : end : step , start : end : step]
        #ROW                   #COLUMN

## Basic Functions

### broadcasting

In [38]:
arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,1]])
# Adding,subtracting, multiply, squaring 1 to every element
print(arr+1, arr-1,arr*10, arr**2)

[[2 3 4 5]
 [6 3 5 3]
 [2 3 1 2]] [[ 0  1  2  3]
 [ 4  1  3  1]
 [ 0  1 -1  0]] [[10 20 30 40]
 [50 20 40 20]
 [10 20  0 10]] [[ 1  4  9 16]
 [25  4 16  4]
 [ 1  4  0  1]]


In [39]:
#Transpose of an Array
print(arr.T)

[[1 5 1]
 [2 2 2]
 [3 4 0]
 [4 2 1]]


In [44]:
#Largest element is :
print(arr.max())
# Rowwise max element
print(arr.max(axis = 1))
# Columnwise max element
print(arr.max(axis = 0))
# sum of all elements
print(arr.sum())
# cummulative sum along each row
print(arr.cumsum(axis = 1))

5
[4 5 2]
[5 2 4 4]
27
[[ 1  3  6 10]
 [ 5  7 11 13]
 [ 1  3  3  4]]


## Arithmetic Operations

In [46]:
a = np.array([[1,2],
             [2,3]])
b = np.array([[4,3],
             [2,1]])
print(a+b)
print(a*b)
print(a.dot(b))

[[5 5]
 [4 4]]
[[4 6]
 [4 3]]
[[ 8  5]
 [14  9]]


In [47]:
a = np.array([0,np.pi/2, np.pi])
print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [48]:
np.exp(a)

array([ 1.        ,  4.81047738, 23.14069263])

In [49]:
np.sqrt(a)

array([0.        , 1.25331414, 1.77245385])

## Sorting Array

In [50]:
ar = np.array([[1,4,2],
              [3,4,6],
              [0,-1,5]])
print(np.sort(ar,axis = None))

[-1  0  1  2  3  4  4  5  6]


In [51]:
print(np.sort(ar,axis = 1)) # Row-wise sorted array

[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [52]:
np.sort(ar,axis = 0, kind = 'mergesort')

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

## Stacking and Splitting

In [53]:
a = np.array([[1,2],
             [2,3]])
b = np.array([[4,3],
             [2,1]])
np.vstack((a,b)) # vertical stacking

array([[1, 2],
       [2, 3],
       [4, 3],
       [2, 1]])

In [57]:
np.hstack((a,b)) # horizontal stack

array([[1, 2, 4, 3],
       [2, 3, 2, 1]])

In [58]:
e = [5,6]
np.column_stack((a,e))

array([[1, 2, 5],
       [2, 3, 6]])

In [59]:
np.concatenate((a,b),1)

array([[1, 2, 4, 3],
       [2, 3, 2, 1]])

In [60]:
a = np.array([[1,3,5,7,9,11],
             [2,4,5,8,10,12]])
np.hsplit(a,2)

[array([[1, 3, 5],
        [2, 4, 5]]),
 array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [61]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  5,  8, 10, 12]])]

## Statistics in NumPy

In [64]:
np.min(a, axis = 0)

array([ 1,  3,  5,  7,  9, 11])

In [65]:
np.min(a, axis = 1)

array([1, 2])

In [66]:
np.median(a)

6.0

In [67]:
np.mean(a)

6.416666666666667

In [68]:
np.var(a)

12.076388888888888

In [69]:
np.average(a)

6.416666666666667

## Numpy Random Module

In [70]:
a = np.arange(10) + 5
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[11 10  6  5  7  9 14 12 13  8]


In [75]:
a = np.random.randn(2,3)
a

array([[ 0.85817886,  0.07134299, -2.29230928],
       [-1.41555249,  0.8858294 ,  0.63190187]])

In [77]:
ele = np.random.randint(5,10,3)
ele

array([9, 6, 5])

In [78]:
ele = np.random.choice([1,4,3,2,11,27])
ele

1