# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
arr = np.zeros((5, 5))
mem_size = arr.nbytes
print("Memory size of the array: ", mem_size, "bytes")

Memory size of the array:  200 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [11]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [13]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [18]:
vec = np.arange(10,49)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last)

In [19]:
arr = [5,4,3,2,1]
print(arr[::-1])

[1, 2, 3, 4, 5]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
arr = np.arange(9)
matrix = arr.reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [26]:
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [28]:
mat = np.eye(3,3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [29]:
arr = np.random.rand(3,3,3)
print(arr)

[[[0.24677822 0.31374279 0.02011648]
  [0.49806663 0.39890722 0.16721062]
  [0.77650982 0.66799804 0.3637716 ]]

 [[0.92312837 0.49034796 0.7734815 ]
  [0.34896797 0.30342101 0.04986383]
  [0.60506853 0.75191294 0.47275896]]

 [[0.49390401 0.358408   0.15068036]
  [0.18163463 0.69873915 0.12622418]
  [0.2525039  0.05103206 0.29544761]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [33]:
arr = np.random.rand(10, 10)
min_val = np.min(arr)
max_val = np.max(arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Minimum value: 0.0018600389353021773
Maximum value: 0.9951615968454703


#### 14. Create a random vector of size 30 and find the mean value

In [36]:
v = np.random.rand(30)
np.mean(v)

0.4585741368425344

#### 15. Create a 2d array with 1 on the border and 0 inside

In [39]:
arr = np.random.rand(10,10)
arr[1:9,1:9] = 0
arr[0,:] = 1
arr[:,0] = 1
arr[9,:] = 1
arr[:,9] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [42]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

bordered_arr = np.zeros((5,5), dtype=arr.dtype)
bordered_arr[1:-1,1:-1] = arr
print(bordered_arr)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
arr = np.diag([1, 2, 3, 4], k=-1)
zeros_arr = np.zeros((5, 5), dtype=int)
result_arr = zeros_arr + arr
print(result_arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [46]:
matrix = np.zeros((8, 8), dtype=int)
matrix[::2,::2] = 1
matrix[1::2,1::2] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
import math
shape = (6, 7, 8)
linear_index = 99
dim_x, dim_y, dim_z = shape
z = math.floor(linear_index / (dim_x * dim_y))
y = math.floor((linear_index - z * dim_x * dim_y) / dim_x)
x = linear_index % dim_x
print("Index of the 100th element:", (x, y, z))

Index of the 100th element: (3, 2, 2)
